values:
  ACACIA_DOOR: 6
  ACACIA_FENCE: 3
  ACACIA_FENCE_GATE: 3
  ACACIA_HANGING_SIGN: 4
  ACACIA_LEAVES: 2
  ACACIA_LOG: 4
  ACACIA_PLANKS: 2
  ACACIA_SAPLING: 2
  ACACIA_SIGN: 4
  ACACIA_SLAB: 2
  ACACIA_STAIRS: 4
  ACACIA_TRAPDOOR: 4
  ACACIA_WOOD: 4
  ALLIUM: 3
  ANDESITE: 4
  ANDESITE_SLAB: 2
  ANDESITE_STAIRS: 4
  ANDESITE_WALL: 3
  AZALEA: 3
  AZALEA_LEAVES: 2
  AZURE_BLUET: 3
  BAMBOO: 3
  BAMBOO_BLOCK: 4
  BAMBOO_DOOR: 6
  BAMBOO_FENCE: 3
  BAMBOO_FENCE_GATE: 3
  BAMBOO_HANGING_SIGN: 4
  BAMBOO_MOSAIC: 4
  BAMBOO_MOSAIC_SLAB: 2
  BAMBOO_MOSAIC_STAIRS: 4
  BAMBOO_PLANKS: 2
  BAMBOO_SIGN: 4
  BAMBOO_SLAB: 2
  BAMBOO_STAIRS: 4
  BAMBOO_TRAPDOOR: 4
  BASALT: 4
  BIG_DRIPLEAF: 3
  BIG_DRIPLEAF_STEM: 4
  BIRCH_DOOR: 6
  BIRCH_FENCE: 3
  BIRCH_FENCE_GATE: 3
  BIRCH_HANGING_SIGN: 4
  BIRCH_LEAVES: 2
  BIRCH_LOG: 4
  BIRCH_PLANKS: 2
  BIRCH_SAPLING: 2
  BIRCH_SIGN: 4
  BIRCH_SLAB: 2
  BIRCH_STAIRS: 4
  BIRCH_TRAPDOOR: 4
  BIRCH_WOOD: 4
  BLACKSTONE: 4
  BLACKSTONE_SLAB: 2
  BLACKSTONE_STAIRS: 4
  BLACKSTONE_WALL: 3
  BLACK_BANNER: 8
  BLACK_BED: 10
  BLACK_CANDLE: 3
  BLACK_CARPET: 2
  BLACK_CONCRETE: 5
  BLACK_CONCRETE_POWDER: 4
  BLACK_GLAZED_TERRACOTTA: 8
  BLACK_STAINED_GLASS: 3
  BLACK_STAINED_GLASS_PANE: 2
  BLACK_TERRACOTTA: 5
  BLACK_WOOL: 3
  BLUE_BANNER: 8
  BLUE_BED: 10
  BLUE_CANDLE: 3
  BLUE_CARPET: 2
  BLUE_CONCRETE: 5
  BLUE_CONCRETE_POWDER: 4
  BLUE_GLAZED_TERRACOTTA: 8
  BLUE_ICE: 3
  BLUE_ORCHID: 3
  BLUE_STAINED_GLASS: 3
  BLUE_STAINED_GLASS_PANE: 2
  BLUE_TERRACOTTA: 5
  BLUE_WOOL: 3
  BRAIN_CORAL: 3
  BRAIN_CORAL_BLOCK: 4
  BRAIN_CORAL_FAN: 3
  BRICKS: 4
  BRICK_SLAB: 2
  BRICK_STAIRS: 4
  BRICK_WALL: 3
  BROWN_BANNER: 8
  BROWN_BED: 10
  BROWN_CANDLE: 3
  BROWN_CARPET: 2
  BROWN_CONCRETE: 5
  BROWN_CONCRETE_POWDER: 4
  BROWN_GLAZED_TERRACOTTA: 8
  BROWN_MUSHROOM: 3
  BROWN_MUSHROOM_BLOCK: 4
  BROWN_STAINED_GLASS: 3
  BROWN_STAINED_GLASS_PANE: 2
  BROWN_TERRACOTTA: 5
  BROWN_WOOL: 3
  BUBBLE_CORAL: 3
  BUBBLE_CORAL_BLOCK: 4
  BUBBLE_CORAL_FAN: 3
  BUSH: 4
  CACTUS: 3
  CACTUS_FLOWER: 4
  CALCITE: 4
  CAMPFIRE: 4
  CAVE_VINES: 3
  CAVE_VINES_PLANT: 3
  CHERRY_DOOR: 6
  CHERRY_FENCE: 3
  CHERRY_FENCE_GATE: 3
  CHERRY_HANGING_SIGN: 4
  CHERRY_LEAVES: 2
  CHERRY_LOG: 4
  CHERRY_PLANKS: 2
  CHERRY_SAPLING: 2
  CHERRY_SIGN: 4
  CHERRY_SLAB: 2
  CHERRY_STAIRS: 4
  CHERRY_TRAPDOOR: 4
  CHERRY_WOOD: 4
  CHISELED_COPPER: 8
  CHISELED_DEEPSLATE: 4
  CHISELED_NETHER_BRICKS: 4
  CHISELED_POLISHED_BLACKSTONE: 4
  CHISELED_QUARTZ_BLOCK: 4
  CHISELED_RED_SANDSTONE: 4
  CHISELED_RESIN_BRICKS: 6
  CHISELED_SANDSTONE: 4
  CHISELED_STONE_BRICKS: 4
  CHISELED_TUFF: 4
  CHISELED_TUFF_BRICKS: 4
  CLAY: 3
  CLOSED_EYEBLOSSOM: 4
  COARSE_DIRT: 2
  COBBLED_DEEPSLATE: 4
  COBBLED_DEEPSLATE_SLAB: 2
  COBBLED_DEEPSLATE_STAIRS: 4
  COBBLED_DEEPSLATE_WALL: 3
  COBBLESTONE: 4
  COBBLESTONE_SLAB: 2
  COBBLESTONE_STAIRS: 4
  COBBLESTONE_WALL: 3
  COBWEB: 4
  COPPER_BARS: 8
  COPPER_CHAIN: 8
  COPPER_DOOR: 6
  COPPER_GRATE: 8
  COPPER_LANTERN: 12
  COPPER_TORCH: 8
  COPPER_TRAPDOOR: 4
  CORNFLOWER: 3
  CRACKED_DEEPSLATE_BRICKS: 4
  CRACKED_DEEPSLATE_TILES: 4
  CRACKED_NETHER_BRICKS: 4
  CRACKED_POLISHED_BLACKSTONE_BRICKS: 4
  CRACKED_STONE_BRICKS: 4
  CRIMSON_DOOR: 6
  CRIMSON_FENCE: 3
  CRIMSON_FENCE_GATE: 3
  CRIMSON_FUNGUS: 3
  CRIMSON_HANGING_SIGN: 4
  CRIMSON_HYPHAE: 4
  CRIMSON_NYLIUM: 4
  CRIMSON_PLANKS: 2
  CRIMSON_ROOTS: 3
  CRIMSON_SIGN: 4
  CRIMSON_SLAB: 2
  CRIMSON_STAIRS: 4
  CRIMSON_STEM: 4
  CRIMSON_TRAPDOOR: 4
  CUT_COPPER: 8
  CUT_COPPER_SLAB: 2
  CUT_COPPER_STAIRS: 4
  CUT_RED_SANDSTONE: 4
  CUT_RED_SANDSTONE_SLAB: 2
  CUT_SANDSTONE: 4
  CUT_SANDSTONE_SLAB: 2
  CYAN_BANNER: 8
  CYAN_BED: 10
  CYAN_CANDLE: 3
  CYAN_CARPET: 2
  CYAN_CONCRETE: 5
  CYAN_CONCRETE_POWDER: 4
  CYAN_GLAZED_TERRACOTTA: 8
  CYAN_STAINED_GLASS: 3
  CYAN_STAINED_GLASS_PANE: 2
  CYAN_TERRACOTTA: 5
  CYAN_WOOL: 3
  DANDELION: 3
  DARK_OAK_DOOR: 6
  DARK_OAK_FENCE: 3
  DARK_OAK_FENCE_GATE: 3
  DARK_OAK_HANGING_SIGN: 4
  DARK_OAK_LEAVES: 2
  DARK_OAK_LOG: 4
  DARK_OAK_PLANKS: 2
  DARK_OAK_SAPLING: 2
  DARK_OAK_SIGN: 4
  DARK_OAK_SLAB: 2
  DARK_OAK_STAIRS: 4
  DARK_OAK_TRAPDOOR: 4
  DARK_OAK_WOOD: 4
  DARK_PRISMARINE: 4
  DARK_PRISMARINE_SLAB: 2
  DARK_PRISMARINE_STAIRS: 4
  DEAD_BRAIN_CORAL: 3
  DEAD_BRAIN_CORAL_BLOCK: 4
  DEAD_BRAIN_CORAL_FAN: 3
  DEAD_BUBBLE_CORAL: 3
  DEAD_BUBBLE_CORAL_BLOCK: 4
  DEAD_BUBBLE_CORAL_FAN: 3
  DEAD_BUSH: 3
  DEAD_FIRE_CORAL: 3
  DEAD_FIRE_CORAL_BLOCK: 4
  DEAD_FIRE_CORAL_FAN: 3
  DEAD_HORN_CORAL: 3
  DEAD_HORN_CORAL_BLOCK: 4
  DEAD_HORN_CORAL_FAN: 3
  DEAD_TUBE_CORAL: 3
  DEAD_TUBE_CORAL_BLOCK: 4
  DEAD_TUBE_CORAL_FAN: 3
  DEEPSLATE: 4
  DEEPSLATE_BRICKS: 4
  DEEPSLATE_BRICK_SLAB: 2
  DEEPSLATE_BRICK_STAIRS: 4
  DEEPSLATE_BRICK_WALL: 3
  DEEPSLATE_TILES: 4
  DEEPSLATE_TILE_SLAB: 2
  DEEPSLATE_TILE_STAIRS: 4
  DEEPSLATE_TILE_WALL: 3
  DIORITE: 4
  DIORITE_SLAB: 2
  DIORITE_STAIRS: 4
  DIORITE_WALL: 3
  DIRT: 2
  DRIPSTONE_BLOCK: 4
  END_ROD: 10
  END_STONE: 4
  END_STONE_BRICKS: 4
  END_STONE_BRICK_SLAB: 2
  END_STONE_BRICK_STAIRS: 4
  END_STONE_BRICK_WALL: 3
  EXPOSED_CHISELED_COPPER: 8
  EXPOSED_COPPER_BARS: 8
  EXPOSED_COPPER_CHAIN: 8
  EXPOSED_COPPER_DOOR: 6
  EXPOSED_COPPER_GRATE: 8
  EXPOSED_COPPER_LANTERN: 12
  EXPOSED_COPPER_TRAPDOOR: 4
  EXPOSED_CUT_COPPER: 8
  EXPOSED_CUT_COPPER_SLAB: 2
  EXPOSED_CUT_COPPER_STAIRS: 4
  FERN: 3
  FIREFLY_BUSH: 4
  FIRE_CORAL: 3
  FIRE_CORAL_BLOCK: 4
  FIRE_CORAL_FAN: 3
  FLOWERING_AZALEA: 3
  FLOWERING_AZALEA_LEAVES: 2
  FLOWER_POT: 4
  GLASS: 3
  GLASS_PANE: 2
  GLOWSTONE: 4
  GLOW_LICHEN: 3
  GOLDEN_DANDELION: 4
  GRANITE: 4
  GRANITE_SLAB: 2
  GRANITE_STAIRS: 4
  GRANITE_WALL: 3
  GRASS_BLOCK: 2
  GRAVEL: 2
  GRAY_BANNER: 8
  GRAY_BED: 10
  GRAY_CANDLE: 3
  GRAY_CARPET: 2
  GRAY_CONCRETE: 5
  GRAY_CONCRETE_POWDER: 4
  GRAY_GLAZED_TERRACOTTA: 8
  GRAY_STAINED_GLASS: 3
  GRAY_STAINED_GLASS_PANE: 2
  GRAY_TERRACOTTA: 5
  GRAY_WOOL: 3
  GREEN_BANNER: 8
  GREEN_BED: 10
  GREEN_CANDLE: 3
  GREEN_CARPET: 2
  GREEN_CONCRETE: 5
  GREEN_CONCRETE_POWDER: 4
  GREEN_GLAZED_TERRACOTTA: 8
  GREEN_STAINED_GLASS: 3
  GREEN_STAINED_GLASS_PANE: 2
  GREEN_TERRACOTTA: 5
  GREEN_WOOL: 3
  HANGING_ROOTS: 3
  HORN_CORAL: 3
  HORN_CORAL_BLOCK: 4
  HORN_CORAL_FAN: 3
  ICE: 3
  IRON_BARS: 4
  IRON_CHAIN: 4
  JACK_O_LANTERN: 10
  JUNGLE_DOOR: 6
  JUNGLE_FENCE: 3
  JUNGLE_FENCE_GATE: 3
  JUNGLE_HANGING_SIGN: 4
  JUNGLE_LEAVES: 2
  JUNGLE_LOG: 4
  JUNGLE_PLANKS: 2
  JUNGLE_SAPLING: 2
  JUNGLE_SIGN: 4
  JUNGLE_SLAB: 2
  JUNGLE_STAIRS: 4
  JUNGLE_TRAPDOOR: 4
  JUNGLE_WOOD: 4
  KELP: 3
  KELP_PLANT: 3
  LADDER: 4
  LANTERN: 10
  LARGE_FERN: 3
  LEAF_LITTER: 4
  LIGHT_BLUE_BANNER: 8
  LIGHT_BLUE_BED: 10
  LIGHT_BLUE_CANDLE: 3
  LIGHT_BLUE_CARPET: 2
  LIGHT_BLUE_CONCRETE: 5
  LIGHT_BLUE_CONCRETE_POWDER: 4
  LIGHT_BLUE_GLAZED_TERRACOTTA: 8
  LIGHT_BLUE_STAINED_GLASS: 3
  LIGHT_BLUE_STAINED_GLASS_PANE: 2
  LIGHT_BLUE_TERRACOTTA: 5
  LIGHT_BLUE_WOOL: 3
  LIGHT_GRAY_BANNER: 8
  LIGHT_GRAY_BED: 10
  LIGHT_GRAY_CANDLE: 3
  LIGHT_GRAY_CARPET: 2
  LIGHT_GRAY_CONCRETE: 5
  LIGHT_GRAY_CONCRETE_POWDER: 4
  LIGHT_GRAY_GLAZED_TERRACOTTA: 8
  LIGHT_GRAY_STAINED_GLASS: 3
  LIGHT_GRAY_STAINED_GLASS_PANE: 2
  LIGHT_GRAY_TERRACOTTA: 5
  LIGHT_GRAY_WOOL: 3
  LILAC: 3
  LILY_OF_THE_VALLEY: 3
  LILY_PAD: 3
  LIME_BANNER: 8
  LIME_BED: 10
  LIME_CANDLE: 3
  LIME_CARPET: 2
  LIME_CONCRETE: 5
  LIME_CONCRETE_POWDER: 4
  LIME_GLAZED_TERRACOTTA: 8
  LIME_STAINED_GLASS: 3
  LIME_STAINED_GLASS_PANE: 2
  LIME_TERRACOTTA: 5
  LIME_WOOL: 3
  MAGENTA_BANNER: 8
  MAGENTA_BED: 10
  MAGENTA_CANDLE: 3
  MAGENTA_CARPET: 2
  MAGENTA_CONCRETE: 5
  MAGENTA_CONCRETE_POWDER: 4
  MAGENTA_GLAZED_TERRACOTTA: 8
  MAGENTA_STAINED_GLASS: 3
  MAGENTA_STAINED_GLASS_PANE: 2
  MAGENTA_TERRACOTTA: 5
  MAGENTA_WOOL: 3
  MANGROVE_DOOR: 6
  MANGROVE_FENCE: 3
  MANGROVE_FENCE_GATE: 3
  MANGROVE_HANGING_SIGN: 4
  MANGROVE_LEAVES: 2
  MANGROVE_LOG: 4
  MANGROVE_PLANKS: 2
  MANGROVE_ROOTS: 3
  MANGROVE_SIGN: 4
  MANGROVE_SLAB: 2
  MANGROVE_STAIRS: 4
  MANGROVE_TRAPDOOR: 4
  MANGROVE_WOOD: 4
  MOSSY_COBBLESTONE: 4
  MOSSY_COBBLESTONE_SLAB: 2
  MOSSY_COBBLESTONE_STAIRS: 4
  MOSSY_COBBLESTONE_WALL: 3
  MOSSY_STONE_BRICKS: 4
  MOSSY_STONE_BRICK_SLAB: 2
  MOSSY_STONE_BRICK_STAIRS: 4
  MOSSY_STONE_BRICK_WALL: 3
  MOSS_BLOCK: 4
  MOSS_CARPET: 2
  MUD: 3
  MUDDY_MANGROVE_ROOTS: 3
  MUD_BRICKS: 4
  MUD_BRICK_SLAB: 2
  MUD_BRICK_STAIRS: 4
  MUD_BRICK_WALL: 3
  MUSHROOM_STEM: 4
  MYCELIUM: 3
  NETHERRACK: 4
  NETHER_BRICKS: 4
  NETHER_BRICK_SLAB: 2
  NETHER_BRICK_STAIRS: 4
  NETHER_BRICK_WALL: 3
  NETHER_SPROUTS: 3
  NETHER_WART_BLOCK: 4
  OAK_DOOR: 6
  OAK_FENCE: 3
  OAK_FENCE_GATE: 3
  OAK_HANGING_SIGN: 4
  OAK_LEAVES: 2
  OAK_LOG: 4
  OAK_PLANKS: 2
  OAK_SAPLING: 2
  OAK_SIGN: 4
  OAK_SLAB: 2
  OAK_STAIRS: 4
  OAK_TRAPDOOR: 4
  OAK_WOOD: 4
  OCHRE_FROGLIGHT: 10
  OPEN_EYEBLOSSOM: 4
  ORANGE_BANNER: 8
  ORANGE_BED: 10
  ORANGE_CANDLE: 3
  ORANGE_CARPET: 2
  ORANGE_CONCRETE: 5
  ORANGE_CONCRETE_POWDER: 4
  ORANGE_GLAZED_TERRACOTTA: 8
  ORANGE_STAINED_GLASS: 3
  ORANGE_STAINED_GLASS_PANE: 2
  ORANGE_TERRACOTTA: 5
  ORANGE_TULIP: 3
  ORANGE_WOOL: 3
  OXEYE_DAISY: 3
  OXIDIZED_CHISELED_COPPER: 8
  OXIDIZED_COPPER_BARS: 8
  OXIDIZED_COPPER_CHAIN: 8
  OXIDIZED_COPPER_DOOR: 6
  OXIDIZED_COPPER_GRATE: 8
  OXIDIZED_COPPER_LANTERN: 12
  OXIDIZED_COPPER_TRAPDOOR: 4
  OXIDIZED_CUT_COPPER: 8
  OXIDIZED_CUT_COPPER_SLAB: 2
  OXIDIZED_CUT_COPPER_STAIRS: 4
  PACKED_ICE: 3
  PACKED_MUD: 4
  PALE_HANGING_MOSS: 4
  PALE_MOSS_BLOCK: 4
  PALE_MOSS_CARPET: 2
  PALE_OAK_DOOR: 6
  PALE_OAK_FENCE: 3
  PALE_OAK_FENCE_GATE: 3
  PALE_OAK_HANGING_SIGN: 4
  PALE_OAK_LEAVES: 2
  PALE_OAK_LOG: 4
  PALE_OAK_PLANKS: 2
  PALE_OAK_SAPLING: 2
  PALE_OAK_SIGN: 4
  PALE_OAK_SLAB: 2
  PALE_OAK_STAIRS: 4
  PALE_OAK_TRAPDOOR: 4
  PALE_OAK_WOOD: 4
  PEARLESCENT_FROGLIGHT: 10
  PEONY: 3
  PINK_BANNER: 8
  PINK_BED: 10
  PINK_CANDLE: 3
  PINK_CARPET: 2
  PINK_CONCRETE: 5
  PINK_CONCRETE_POWDER: 4
  PINK_GLAZED_TERRACOTTA: 8
  PINK_PETALS: 3
  PINK_STAINED_GLASS: 3
  PINK_STAINED_GLASS_PANE: 2
  PINK_TERRACOTTA: 5
  PINK_TULIP: 3
  PINK_WOOL: 3
  PODZOL: 3
  POINTED_DRIPSTONE: 3
  POLISHED_ANDESITE: 4
  POLISHED_ANDESITE_SLAB: 2
  POLISHED_ANDESITE_STAIRS: 4
  POLISHED_BASALT: 4
  POLISHED_BLACKSTONE: 4
  POLISHED_BLACKSTONE_BRICKS: 4
  POLISHED_BLACKSTONE_BRICK_SLAB: 2
  POLISHED_BLACKSTONE_BRICK_STAIRS: 4
  POLISHED_BLACKSTONE_BRICK_WALL: 3
  POLISHED_BLACKSTONE_SLAB: 2
  POLISHED_BLACKSTONE_STAIRS: 4
  POLISHED_BLACKSTONE_WALL: 3
  POLISHED_DEEPSLATE: 4
  POLISHED_DEEPSLATE_SLAB: 2
  POLISHED_DEEPSLATE_STAIRS: 4
  POLISHED_DEEPSLATE_WALL: 3
  POLISHED_DIORITE: 4
  POLISHED_DIORITE_SLAB: 2
  POLISHED_DIORITE_STAIRS: 4
  POLISHED_GRANITE: 4
  POLISHED_GRANITE_SLAB: 2
  POLISHED_GRANITE_STAIRS: 4
  POLISHED_TUFF: 4
  POLISHED_TUFF_SLAB: 2
  POLISHED_TUFF_STAIRS: 4
  POLISHED_TUFF_WALL: 3
  POPPY: 3
  PRISMARINE: 4
  PRISMARINE_BRICKS: 4
  PRISMARINE_BRICK_SLAB: 2
  PRISMARINE_BRICK_STAIRS: 4
  PRISMARINE_SLAB: 2
  PRISMARINE_STAIRS: 4
  PRISMARINE_WALL: 3
  PURPLE_BANNER: 8
  PURPLE_BED: 10
  PURPLE_CANDLE: 3
  PURPLE_CARPET: 2
  PURPLE_CONCRETE: 5
  PURPLE_CONCRETE_POWDER: 4
  PURPLE_GLAZED_TERRACOTTA: 8
  PURPLE_STAINED_GLASS: 3
  PURPLE_STAINED_GLASS_PANE: 2
  PURPLE_TERRACOTTA: 5
  PURPLE_WOOL: 3
  PURPUR_BLOCK: 4
  PURPUR_PILLAR: 4
  PURPUR_SLAB: 2
  PURPUR_STAIRS: 4
  QUARTZ_BLOCK: 4
  QUARTZ_BRICKS: 4
  QUARTZ_PILLAR: 4
  QUARTZ_SLAB: 2
  QUARTZ_STAIRS: 4
  RAIL: 3
  RED_BANNER: 8
  RED_BED: 10
  RED_CANDLE: 3
  RED_CARPET: 2
  RED_CONCRETE: 5
  RED_CONCRETE_POWDER: 4
  RED_GLAZED_TERRACOTTA: 8
  RED_MUSHROOM: 3
  RED_MUSHROOM_BLOCK: 4
  RED_NETHER_BRICKS: 4
  RED_NETHER_BRICK_SLAB: 2
  RED_NETHER_BRICK_STAIRS: 4
  RED_NETHER_BRICK_WALL: 3
  RED_SAND: 2
  RED_SANDSTONE: 4
  RED_SANDSTONE_SLAB: 2
  RED_SANDSTONE_STAIRS: 4
  RED_SANDSTONE_WALL: 3
  RED_STAINED_GLASS: 3
  RED_STAINED_GLASS_PANE: 2
  RED_TERRACOTTA: 5
  RED_TULIP: 3
  RED_WOOL: 3
  RESIN_BLOCK: 4
  RESIN_BRICKS: 6
  RESIN_BRICK_SLAB: 2
  RESIN_BRICK_STAIRS: 4
  RESIN_BRICK_WALL: 3
  ROOTED_DIRT: 3
  ROSE_BUSH: 3
  SAND: 2
  SANDSTONE: 4
  SANDSTONE_SLAB: 2
  SANDSTONE_STAIRS: 4
  SANDSTONE_WALL: 3
  SCAFFOLDING: 4
  SEAGRASS: 3
  SEA_LANTERN: 10
  SEA_PICKLE: 3
  SHORT_DRY_GRASS: 3
  SHORT_GRASS: 3
  SHROOMLIGHT: 4
  SMALL_DRIPLEAF: 3
  SMOOTH_BASALT: 4
  SMOOTH_QUARTZ: 4
  SMOOTH_QUARTZ_SLAB: 2
  SMOOTH_QUARTZ_STAIRS: 4
  SMOOTH_RED_SANDSTONE: 4
  SMOOTH_RED_SANDSTONE_SLAB: 2
  SMOOTH_RED_SANDSTONE_STAIRS: 4
  SMOOTH_SANDSTONE: 4
  SMOOTH_SANDSTONE_SLAB: 2
  SMOOTH_SANDSTONE_STAIRS: 4
  SMOOTH_STONE: 4
  SMOOTH_STONE_SLAB: 2
  SNOW: 3
  SNOW_BLOCK: 4
  SOUL_CAMPFIRE: 4
  SOUL_LANTERN: 10
  SOUL_SAND: 4
  SOUL_SOIL: 4
  SOUL_TORCH: 3
  SPORE_BLOSSOM: 3
  SPRUCE_DOOR: 6
  SPRUCE_FENCE: 3
  SPRUCE_FENCE_GATE: 3
  SPRUCE_HANGING_SIGN: 4
  SPRUCE_LEAVES: 2
  SPRUCE_LOG: 4
  SPRUCE_PLANKS: 2
  SPRUCE_SAPLING: 2
  SPRUCE_SIGN: 4
  SPRUCE_SLAB: 2
  SPRUCE_STAIRS: 4
  SPRUCE_TRAPDOOR: 4
  SPRUCE_WOOD: 4
  STONE: 4
  STONE_BRICKS: 4
  STONE_BRICK_SLAB: 2
  STONE_BRICK_STAIRS: 4
  STONE_BRICK_WALL: 3
  STONE_SLAB: 2
  STONE_STAIRS: 4
  STRIPPED_ACACIA_LOG: 4
  STRIPPED_ACACIA_WOOD: 4
  STRIPPED_BAMBOO_BLOCK: 4
  STRIPPED_BIRCH_LOG: 4
  STRIPPED_BIRCH_WOOD: 4
  STRIPPED_CHERRY_LOG: 4
  STRIPPED_CHERRY_WOOD: 4
  STRIPPED_CRIMSON_HYPHAE: 4
  STRIPPED_CRIMSON_STEM: 4
  STRIPPED_DARK_OAK_LOG: 4
  STRIPPED_DARK_OAK_WOOD: 4
  STRIPPED_JUNGLE_LOG: 4
  STRIPPED_JUNGLE_WOOD: 4
  STRIPPED_MANGROVE_LOG: 4
  STRIPPED_MANGROVE_WOOD: 4
  STRIPPED_OAK_LOG: 4
  STRIPPED_OAK_WOOD: 4
  STRIPPED_PALE_OAK_LOG: 4
  STRIPPED_PALE_OAK_WOOD: 4
  STRIPPED_SPRUCE_LOG: 4
  STRIPPED_SPRUCE_WOOD: 4
  STRIPPED_WARPED_HYPHAE: 4
  STRIPPED_WARPED_STEM: 4
  SUNFLOWER: 3
  TALL_DRY_GRASS: 3
  TALL_GRASS: 3
  TALL_SEAGRASS: 3
  TERRACOTTA: 5
  TINTED_GLASS: 3
  TORCH: 3
  TORCHFLOWER: 3
  TUBE_CORAL: 3
  TUBE_CORAL_BLOCK: 4
  TUBE_CORAL_FAN: 3
  TUFF: 4
  TUFF_BRICKS: 4
  TUFF_BRICK_SLAB: 2
  TUFF_BRICK_STAIRS: 4
  TUFF_BRICK_WALL: 3
  TUFF_SLAB: 2
  TUFF_STAIRS: 4
  TUFF_WALL: 3
  TWISTING_VINES: 3
  VERDANT_FROGLIGHT: 10
  VINE: 3
  WARPED_DOOR: 6
  WARPED_FENCE: 3
  WARPED_FENCE_GATE: 3
  WARPED_FUNGUS: 3
  WARPED_HANGING_SIGN: 4
  WARPED_HYPHAE: 4
  WARPED_NYLIUM: 4
  WARPED_PLANKS: 2
  WARPED_ROOTS: 3
  WARPED_SIGN: 4
  WARPED_SLAB: 2
  WARPED_STAIRS: 4
  WARPED_STEM: 4
  WARPED_TRAPDOOR: 4
  WARPED_WART_BLOCK: 4
  WAXED_CHISELED_COPPER: 8
  WAXED_COPPER_BARS: 8
  WAXED_COPPER_CHAIN: 8
  WAXED_COPPER_DOOR: 6
  WAXED_COPPER_GRATE: 8
  WAXED_COPPER_LANTERN: 12
  WAXED_COPPER_TRAPDOOR: 4
  WAXED_CUT_COPPER: 8
  WAXED_CUT_COPPER_SLAB: 2
  WAXED_CUT_COPPER_STAIRS: 4
  WAXED_EXPOSED_CHISELED_COPPER: 8
  WAXED_EXPOSED_COPPER_BARS: 8
  WAXED_EXPOSED_COPPER_CHAIN: 8
  WAXED_EXPOSED_COPPER_DOOR: 6
  WAXED_EXPOSED_COPPER_GRATE: 8
  WAXED_EXPOSED_COPPER_LANTERN: 12
  WAXED_EXPOSED_COPPER_TRAPDOOR: 4
  WAXED_EXPOSED_CUT_COPPER: 8
  WAXED_EXPOSED_CUT_COPPER_SLAB: 2
  WAXED_EXPOSED_CUT_COPPER_STAIRS: 4
  WAXED_OXIDIZED_CHISELED_COPPER: 8
  WAXED_OXIDIZED_COPPER_BARS: 8
  WAXED_OXIDIZED_COPPER_CHAIN: 8
  WAXED_OXIDIZED_COPPER_DOOR: 6
  WAXED_OXIDIZED_COPPER_GRATE: 8
  WAXED_OXIDIZED_COPPER_LANTERN: 12
  WAXED_OXIDIZED_COPPER_TRAPDOOR: 4
  WAXED_OXIDIZED_CUT_COPPER: 8
  WAXED_OXIDIZED_CUT_COPPER_SLAB: 2
  WAXED_OXIDIZED_CUT_COPPER_STAIRS: 4
  WAXED_WEATHERED_CHISELED_COPPER: 8
  WAXED_WEATHERED_COPPER_BARS: 8
  WAXED_WEATHERED_COPPER_CHAIN: 8
  WAXED_WEATHERED_COPPER_DOOR: 6
  WAXED_WEATHERED_COPPER_GRATE: 8
  WAXED_WEATHERED_COPPER_LANTERN: 12
  WAXED_WEATHERED_COPPER_TRAPDOOR: 4
  WAXED_WEATHERED_CUT_COPPER: 8
  WAXED_WEATHERED_CUT_COPPER_SLAB: 2
  WAXED_WEATHERED_CUT_COPPER_STAIRS: 4
  WEATHERED_CHISELED_COPPER: 8
  WEATHERED_COPPER_BARS: 8
  WEATHERED_COPPER_CHAIN: 8
  WEATHERED_COPPER_DOOR: 6
  WEATHERED_COPPER_GRATE: 8
  WEATHERED_COPPER_LANTERN: 12
  WEATHERED_COPPER_TRAPDOOR: 4
  WEATHERED_CUT_COPPER: 8
  WEATHERED_CUT_COPPER_SLAB: 2
  WEATHERED_CUT_COPPER_STAIRS: 4
  WEEPING_VINES: 3
  WHITE_BANNER: 8
  WHITE_BED: 10
  WHITE_CANDLE: 3
  WHITE_CARPET: 2
  WHITE_CONCRETE: 5
  WHITE_CONCRETE_POWDER: 4
  WHITE_GLAZED_TERRACOTTA: 8
  WHITE_STAINED_GLASS: 3
  WHITE_STAINED_GLASS_PANE: 2
  WHITE_TERRACOTTA: 5
  WHITE_TULIP: 3
  WHITE_WOOL: 3
  WILDFLOWERS: 3
  YELLOW_BANNER: 8
  YELLOW_BED: 10
  YELLOW_CANDLE: 3
  YELLOW_CARPET: 2
  YELLOW_CONCRETE: 5
  YELLOW_CONCRETE_POWDER: 4
  YELLOW_GLAZED_TERRACOTTA: 8
  YELLOW_STAINED_GLASS: 3
  YELLOW_STAINED_GLASS_PANE: 2
  YELLOW_TERRACOTTA: 5
  YELLOW_WOOL: 3
modes:
  BLACK_CARPET: buy_only
  BLACK_CONCRETE_POWDER: buy_only
  BLUE_CARPET: buy_only
  BLUE_CONCRETE_POWDER: buy_only
  BROWN_CARPET: buy_only
  BROWN_CONCRETE_POWDER: buy_only
  CYAN_CARPET: buy_only
  CYAN_CONCRETE_POWDER: buy_only
  GRAVEL: buy_only
  GRAY_CARPET: buy_only
  GRAY_CONCRETE_POWDER: buy_only
  GREEN_CARPET: buy_only
  GREEN_CONCRETE_POWDER: buy_only
  LIGHT_BLUE_CARPET: buy_only
  LIGHT_BLUE_CONCRETE_POWDER: buy_only
  LIGHT_GRAY_CARPET: buy_only
  LIGHT_GRAY_CONCRETE_POWDER: buy_only
  LIME_CARPET: buy_only
  LIME_CONCRETE_POWDER: buy_only
  MAGENTA_CARPET: buy_only
  MAGENTA_CONCRETE_POWDER: buy_only
  MOSS_CARPET: buy_only
  ORANGE_CARPET: buy_only
  ORANGE_CONCRETE_POWDER: buy_only
  PALE_MOSS_CARPET: buy_only
  PINK_CARPET: buy_only
  PINK_CONCRETE_POWDER: buy_only
  POINTED_DRIPSTONE: buy_only
  PURPLE_CARPET: buy_only
  PURPLE_CONCRETE_POWDER: buy_only
  RAIL: buy_only
  RED_CARPET: buy_only
  RED_CONCRETE_POWDER: buy_only
  RED_SAND: buy_only
  SAND: buy_only
  SCAFFOLDING: buy_only
  WHITE_CARPET: buy_only
  WHITE_CONCRETE_POWDER: buy_only
  YELLOW_CARPET: buy_only
  YELLOW_CONCRETE_POWDER: buy_only
hidden: []
categories: {}
custom-items: {}
